# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  ci-executor:
    docker:
      - image: REPLACE-ME-WITH-DOCKER-IMAGE
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
      